import { TranslationStrings, Language, HistoricalEntry } from './types';

export const TRANSLATIONS: Record<Language, TranslationStrings> = {
  en: {
    title: "EcoFarm Monitor",
    soilMoisture: "Field Wetness",
    temperature: "Air Temp",
    humidity: "Air Humidity",
    lastUpdated: "Last checked",
    optimal: "Looking Good",
    criticalDry: "Need Water Soon",
    startIrrigation: "Action: Turn on the pump",
    skipIrrigation: "Action: Keep pump off (Rain coming)",
    rainExpected: "Rain is on the way",
    annualTrend: "Past Year History",
    waterUsage: "Water Used (L)",
    moistureTrend: "Water in Soil (%)",
    status: "Farm Status",
    settings: "Settings",
    notifications: "Notification Alerts",
    notifyLowMoisture: "Alert me when soil is dry",
    notifyRain: "Notify me about incoming rain",
    thresholdLabel: "Dryness Threshold",
    save: "Save Changes",
    cancel: "Cancel",
    weatherSummary24h: "Last 24 Hours Weather",
    avgTemp: "Average Temperature",
    totalPrecipitation: "Total Rain",
    fieldControls: "Field Controls",
    sprinklerStatus: "Sprinkler Status",
    manualOverride: "Manual Override",
    automation: "Smart Scheduling",
    nextRun: "Next Run",
    scheduler: "Timer Settings",
    turnOn: "Turn ON",
    turnOff: "Turn OFF",
    monitorTab: "Farm Monitor",
    chatTab: "Agro AI Chat",
    videoTab: "Video Lab",
    voiceTab: "Voice Center",
    chatExpertHero: "AgroAI Expert",
    chatOnlineStatus: "Agricultural Consultant • Online",
    chatPlaceholder: "Describe your farming challenge...",
    chatDrafting: "Drafting response...",
    chatClearTooltip: "Clear Conversation",
    chatWelcome: "How can I assist your farm?",
    chatSubtitle: "Ask about crop health, irrigation, pests, or modern farming techniques.",
    chatStarters: [
      "How can I improve soil nitrogen naturally?",
      "What are the best pest control methods for corn?",
      "Recommend an irrigation schedule for tomatoes.",
      "Signs of nutrient deficiency in wheat leaves."
    ],
    aiVisionActive: "AI Vision Active",
    liveFeed: "Live Feed • Sector 04-B",
    aiEnhanced: "AI-Enhanced",
    criticalAction: "Critical Action Required: Field 04-B",
    dataInsights: "Data Insights",
    systemLive: "System Live",
    encryptedNode: "Encrypted Node",
    crops: {
      corn: "Corn",
      wheat: "Wheat",
      tomato: "Tomato",
      apple: "Apple"
    },
    irrigationForecastTitle: "3-Day Irrigation Forecast",
    rainLabel: "Rain",
    irrigationGuidance: "Irrigation Guidance",
    rainWarning: "High probability of rain. Consider pausing automated cycles to conserve water.",
    stableConditions: "Stable conditions expected. Maintain scheduled irrigation to ensure constant soil hydration.",
    windUnit: "km/h",
    midnightToCurrent: "Midnight to Current",
    peakWind: "Peak Wind",
    avgHumidity: "Avg Humidity",
    historicalEfficiencyReport: "Historical Efficiency Report",
    last12Months: "Last 12 Months",
    irrigationAutomationTitle: "Irrigation Automation",
    smartSchedulingDescription: "Adjusts schedules based on rain forecast and soil moisture",
    smartSchedulingEnabled: "Smart Control Active",
    smartSchedulingDisabled: "Fixed Schedule Only",
    statusWorking: "Working",
    statusIdle: "Idle",
    cropHealthTitle: "Crop Health Monitor",
    cropHealthSubtitle: "Real-time AI analysis of field sectors",
    nitrogenLevel: "Nitrogen",
    pestRisk: "Pest Risk",
    hydration: "Hydration",
    low: "Low",
    medium: "Med",
    high: "High",
    healthy: "Healthy",
    warning: "Warning"
  },
  hi: {
    title: "इकोफार्म मॉनिटर",
    soilMoisture: "खेत की नमी",
    temperature: "हवा का तापमान",
    humidity: "हवा की नमी",
    lastUpdated: "पिछली जांच",
    optimal: "सब ठीक है",
    criticalDry: "पानी की जरूरत है",
    startIrrigation: "कार्रवाई: पंप चालू करें",
    skipIrrigation: "कार्रवाई: पंप बंद रखें (बारिश होने वाली है)",
    rainExpected: "आज बारिश की संभावना",
    annualTrend: "पिछले साल का रिकॉर्ड",
    waterUsage: "पानी का उपयोग (ली)",
    moistureTrend: "मिट्टी में पानी (%)",
    status: "खेत की स्थिति",
    settings: "सेटिंग्स",
    notifications: "सूचना अलर्ट",
    notifyLowMoisture: "मिट्टी सूखने पर मुझे सचेत करें",
    notifyRain: "आने वाली बारिश के बारे में मुझे सूचित करें",
    thresholdLabel: "सूखे की सीमा",
    save: "बदलाव सहेजें",
    cancel: "रद्द करें",
    weatherSummary24h: "पिछले 24 घंटों का मौसम",
    avgTemp: "औसत तापमान",
    totalPrecipitation: "कुल बारिश",
    fieldControls: "खेत नियंत्रण",
    sprinklerStatus: "छिड़काव की स्थिति",
    manualOverride: "मैनुअल नियंत्रण",
    automation: "स्मार्ट निर्धारण",
    nextRun: "अगला छिड़काव",
    scheduler: "समय सेटिंग",
    turnOn: "चालू करें",
    turnOff: "बंद करें",
    monitorTab: "फार्म मॉनिटर",
    chatTab: "एग्रो एआई चैट",
    videoTab: "वीडियो लैब",
    voiceTab: "वॉयस सेंटर",
    chatExpertHero: "एग्रो एआई विशेषज्ञ",
    chatOnlineStatus: "कृषि सलाहकार • ऑनलाइन",
    chatPlaceholder: "अपनी खेती की समस्या बताएं...",
    chatDrafting: "जवाब तैयार कर रहा है...",
    chatClearTooltip: "बातचीत साफ़ करें",
    chatWelcome: "मैं आपकी खेती में कैसे मदद कर सकता हूँ?",
    chatSubtitle: "फसल स्वास्थ्य, सिंचाई, कीटों या आधुनिक खेती की तकनीक के बारे में पूछें।",
    chatStarters: [
      "मैं मिट्टी के नाइट्रोजन को प्राकृतिक रूप से कैसे सुधार सकता हूँ?",
      "मक्के के लिए सबसे अच्छे कीट नियंत्रण के तरीके क्या हैं?",
      "टमाटर के लिए सिंचाई कार्यक्रम की सिफारिश करें।",
      "गेहूं की पत्तियों में पोषक तत्वों की कमी के लक्षण।"
    ],
    aiVisionActive: "एआई विजन सक्रिय",
    liveFeed: "लाइव फीड • सेक्टर 04-B",
    aiEnhanced: "एआई-संवर्धित",
    criticalAction: "महत्वपूर्ण कार्रवाई आवश्यक: क्षेत्र 04-B",
    dataInsights: "डेटा अंतर्दृष्टि",
    systemLive: "सिस्टम लाइव",
    encryptedNode: "एन्क्रिप्टेड नोड",
    crops: {
      corn: "मक्का",
      wheat: "गेहूं",
      tomato: "टमाटर",
      apple: "सेब"
    },
    irrigationForecastTitle: "3-दिवसीय सिंचाई पूर्वानुमान",
    rainLabel: "बारिश",
    irrigationGuidance: "सिंचाई मार्गदर्शन",
    rainWarning: "बारिश की उच्च संभावना। पानी बचाने के लिए स्वचालित चक्रों को रोकने पर विचार करें।",
    stableConditions: "स्थिर स्थिति की उम्मीद। निरंतर मिट्टी के जलयोजन सुनिश्चित करने के लिए निर्धारित सिंचाई बनाए रखें।",
    windUnit: "किमी/घंटा",
    midnightToCurrent: "आधी रात से वर्तमान तक",
    peakWind: "चोटी हवा",
    avgHumidity: "औसत आर्द्रता",
    historicalEfficiencyReport: "ऐतिहासिक दक्षता रिपोर्ट",
    last12Months: "पिछले १२ महीने",
    irrigationAutomationTitle: "सिंचाई स्वचालन",
    smartSchedulingDescription: "बारिश के पूर्वानुमान और मिट्टी की नमी के आधार पर कार्यक्रम को समायोजित करता है",
    smartSchedulingEnabled: "स्मार्ट कंट्रोल सक्रिय",
    smartSchedulingDisabled: "केवल निश्चित कार्यक्रम",
    statusWorking: "कार्यरत",
    statusIdle: "निष्क्रिय",
    cropHealthTitle: "फसल स्वास्थ्य मॉनिटर",
    cropHealthSubtitle: "क्षेत्र क्षेत्रों का रीयल-टाइम एआई विश्लेषण",
    nitrogenLevel: "नाइट्रोजन",
    pestRisk: "कीट जोखिम",
    hydration: "जलयोजन",
    low: "कम",
    medium: "मध्यम",
    high: "उच्च",
    healthy: "स्वस्थ",
    warning: "चेतावनी"
  }
};

export const HISTORICAL_DATA: HistoricalEntry[] = [
  { month: 'Jan', avgMoisture: 38, waterUsage: 450 },
  { month: 'Feb', avgMoisture: 42, waterUsage: 380 },
  { month: 'Mar', avgMoisture: 35, waterUsage: 520 },
  { month: 'Apr', avgMoisture: 30, waterUsage: 610 },
  { month: 'May', avgMoisture: 28, waterUsage: 680 },
  { month: 'Jun', avgMoisture: 32, waterUsage: 540 },
  { month: 'Jul', avgMoisture: 45, waterUsage: 250 },
  { month: 'Aug', avgMoisture: 48, waterUsage: 220 },
  { month: 'Sep', avgMoisture: 40, waterUsage: 410 },
  { month: 'Oct', avgMoisture: 36, waterUsage: 480 },
  { month: 'Nov', avgMoisture: 34, waterUsage: 510 },
  { month: 'Dec', avgMoisture: 37, waterUsage: 460 },
];
